### ISSUE TITLE
Ultra Street Fighter II The Final.Challengers weird issues

### ISSUE THREAD

**Issue by ReaperOfSouls1909** [gdkchan/Ryujinx#231]
my bad GDKchan is right main was renamed for yuzu long ago here was the log anyway closing now

`Unhandled Exception: System.NotImplementedException: fsp-srv IFileSystemProxy: 202
   at Ryujinx.HLE.OsHle.Services.IpcService.CallMethod(ServiceCtx Context) in C:\projects\ryujinx\Ryujinx.HLE\OsHle\Services\IpcService.cs:line 74
   at Ryujinx.HLE.OsHle.Ipc.IpcHandler.IpcCall(Switch Ns, Process Process, AMemory Memory, KSession Session, IpcMessage Request, Int64 CmdPtr) in C:\projects\ryujinx\Ryujinx.HLE\OsHle\Ipc\IpcHandler.cs:line 32
   at Ryujinx.HLE.OsHle.Kernel.SvcHandler.SendSyncRequest(AThreadState ThreadState, Int64 CmdPtr, Int64 Size, Int32 Handle) in C:\projects\ryujinx\Ryujinx.HLE\OsHle\Kernel\SvcSystem.cs:line 246
   at Ryujinx.HLE.OsHle.Kernel.SvcHandler.SvcSendSyncRequest(AThreadState ThreadState) in C:\projects\ryujinx\Ryujinx.HLE\OsHle\Kernel\SvcSystem.cs:line 221
   at Ryujinx.HLE.OsHle.Kernel.SvcHandler.SvcCall(Object sender, AInstExceptionEventArgs e) in C:\projects\ryujinx\Ryujinx.HLE\OsHle\Kernel\SvcHandler.cs:line 105
   at _ZN2nn3svc7aarch644lp6415SendSyncRequestENS0_6HandleE(AThreadState , AMemory )
   at ChocolArm64.ATranslator.ExecuteSubroutineA64(AThreadState State, AMemory Memory, Int64 Position) in C:\projects\ryujinx\ChocolArm64\ATranslator.cs:line 88
   at ChocolArm64.AThread.<Execute>b__18_0() in C:\projects\ryujinx\ChocolArm64\AThread.cs:line 47
   at System.Threading.Thread.ThreadMain_ThreadStart()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()`

**Comment by ReaperOfSouls1909** [comment]
fixed the issue

**Comment by HorrorTroll** [comment]
Here it's on #262, u have to build a local one.

**Comment by legend800** [comment]
Ah, got it. Thanks, I'll work on getting a build together. Last question, I assume the games not even playable at this point, so it might not even be worth the trouble just to get a little further in menus.
