### ISSUE TITLE
System.NotImplementedException: Tid 1 ServiceHid 124

### ISSUE THREAD

**Issue by Cpasjuste** [gdkchan/Ryujinx#55]
Hi,

Since this commit : https://github.com/switchbrew/libnx/commit/e7a4eba71c2aada52182a977c2068667b16b9f2a , Ryujinx is not working anymore with libnx. There's probably an "easy" fix, but i'm not sure i should take a closer look myself as i'm not used to it : 

` 
00000000ms | INFO  > Loading as homebrew.
 00000066ms | INFO  > Image base at 0x0000000008000000.
 00002269ms | INFO  > HID shared memory successfully mapped to 0x000000000b6d7000!

Unhandled Exception: System.NotImplementedException: Tid 1 ServiceHid 124
   at Ryujinx.Core.OsHle.Ipc.IpcHandler.IpcCall(Switch Ns, Process Process, AMemory Memory, HSession Session, IpcMessage Request, Int32 ThreadId, Int64 CmdPtr, Int32 HndId) in /home/cpasjuste/dev/switch/Ryujinx/Ryujinx.Core/OsHle/Ipc/IpcHandler.cs:line 119
   at Ryujinx.Core.OsHle.Svc.SvcHandler.SendSyncRequest(AThreadState ThreadState, Boolean UserBuffer) in /home/cpasjuste/dev/switch/Ryujinx/Ryujinx.Core/OsHle/Svc/SvcSystem.cs:line 129
   at Ryujinx.Core.OsHle.Svc.SvcHandler.SvcCall(Object sender, AInstExceptionEventArgs e) in /home/cpasjuste/dev/switch/Ryujinx/Ryujinx.Core/OsHle/Svc/SvcHandler.cs:line 86
   at Sub0000000008cd42e8(AThreadState , AMemory )
   at ChocolArm64.ATranslator.ExecuteSubroutine(AThread Thread, Int64 Position) in /home/cpasjuste/dev/switch/Ryujinx/ChocolArm64/ATranslator.cs:line 65
   at ChocolArm64.AThread.<Execute>b__18_0() in /home/cpasjuste/dev/switch/Ryujinx/ChocolArm64/AThread.cs:line 45
   at System.Threading.Thread.ThreadMain_ThreadStart()
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)

Process finished with exit code 134 (interrupted by signal 6: SIGABRT)
`

**Comment by gdkchan** [comment]
Should be fixed with 4d90d60119992556b28cde119e9a94b8ac4aebf8, can you retest?

**Comment by Cpasjuste** [comment]
Working perfectly, thanks :)
